In [1]:
#importing pandas
import pandas as pd

In [2]:
#check the version of pandas library that we are using
pd.__version__

'2.3.3'

In [3]:
#pandas series with python lists
lst=[1,2,3,4,5,6]
print(lst)

[1, 2, 3, 4, 5, 6]

In [4]:
series=pd.Series(lst)
print(series)
print(type(series))
#series is better than list as ir adds index to the list

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
empty=pd.Series([])
print (empty)

Series([], dtype: object)

In [6]:
#creating a pandas series with its index
a=pd.Series(['p','q','r','s','t'], index=[10,11,12,13,14])
print(a)

10    p
11    q
12    r
13    s
14    t
dtype: object

In [7]:
#giving name to the series
b=pd.Series(['p','q','r','s','t'], index=[10,11,12,13,14], name='alphabets')
b

10    p
11    q
12    r
13    s
14    t
Name: alphabets, dtype: object

In [8]:
#creating a scalar series means a series with single scalar value
scalar_series=pd.Series(0.5)
print(scalar_series)
#by default index is 0

0    0.5
dtype: float64

In [9]:
scalar_series=pd.Series(0.5,index=[1,2,3])
print(scalar_series)

1    0.5
2    0.5
3    0.5
dtype: float64

In [10]:
#creating pandas series with dictionaries

In [11]:
dict_series=pd.Series({'p':1,'q':2,'r':3,'s':4,'t':5})
dict_series

p    1
q    2
r    3
s    4
t    5
dtype: int64

In [12]:
# print (dict_series[0]) it might brek down in future
print (dict_series['q'])

2

In [13]:
#print(dict_series[0:3]) might break down in future
print(dict_series['p':'t'])

p    1
q    2
r    3
s    4
t    5
dtype: int64

In [14]:
print(max(dict_series))
print(min(dict_series))

5
1

In [15]:
#combining list and dictonaries to get diffrent number of columns
dict_series=pd.Series({'p':[1,5,6],'q':[2,6,7],'r':[3,9,0],'s':[4,4,5],'t':[5,1,2]})
dict_series

p    [1, 5, 6]
q    [2, 6, 7]
r    [3, 9, 0]
s    [4, 4, 5]
t    [5, 1, 2]
dtype: object

In [16]:
# lect 2= pandas DataFrame more better way to represent you data
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [17]:
lst=[1,2,3,4,5]
df=pd.DataFrame(lst)
df

   0
0  1
1  2
2  3
3  4
4  5

In [18]:
lst=[[1,2,3,4,5],[11,12,13,14,15]]
df=pd.DataFrame(lst)
df

    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [19]:
#dictonary key represents column names
a=[{'a':5,'b':7,'c':9,'d':2},
   {'a':4,'b':8,'c':10,'d':12}]
df=pd.DataFrame(a)
df

   a  b   c   d
0  5  7   9   2
1  4  8  10  12

In [20]:
#creating dataframe using padas series
b={'Roll no':pd.Series([1,2,3,4,5]),
  'Maths': pd.Series([67,89,23,90,56]),
  'Physics':pd.Series([12,98,44,42,57])}
df=pd.DataFrame(b)
df

   Roll no  Maths  Physics
0        1     67       12
1        2     89       98
2        3     23       44
3        4     90       42
4        5     56       57

In [21]:
#Reading CSV (Comma Separated Values) as DataFrames
df=pd.read_csv(r'C:\Users\HP\Downloads\customer data.csv')
df
#r indicates raw path

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [22]:
type(df)

pandas.core.frame.DataFrame

In [51]:
#data frame functions
df=pd.read_csv(r'C:\Users\HP\Downloads\customer data.csv', header=1, na_values=['N/A','--'])
df

,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
0,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
1,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
2,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
3,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
4,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,25-02-2020,http://www.berger.net/
...,...,...,...,...,...,...,...,...,...,...,...,...
94,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
95,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
96,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
97,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
98,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [50]:
df.columns
#provide the columns of the data table

Index(['1', 'DD37Cf93aecA6Dc', 'Sheryl', 'Baxter', 'Rasmussen Group',
       'East Leonard', 'Chile', '229.077.5154', '397.884.0519x718',
       'zunigavanessa@smith.info', '24-08-2020', 'http://www.stephenson.com/'],
      dtype='object')

In [24]:
df.shape
#no.of rows and columns

(100, 12)

In [25]:
df.size
#total number of cells

1200

In [26]:
df.head()
#provides the first 5 rows of the dataset

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [27]:
df.head(2)
#provides first 2 rows

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/

In [28]:
df.tail()
#provides the last five rows of the dataset

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [29]:
df.tail(3)
#provides the last 3 rows of the dataset

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [30]:
df.describe()
#description of the numerical deta

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [31]:
df.info()
#provide the concise summary of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [32]:
df2=pd.read_csv(r'C:\Users\HP\Downloads\restaurant_data.csv')
df2.head()

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,NaN,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,NaN,0.1,USA,Delivery,Beverage

In [33]:
df2.shape

(80, 10)

In [34]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rank              80 non-null     int64
 1   restaurant        66 non-null     object
 2   content           65 non-null     object
 3   sales             67 non-null     float64
 4   yoy_sales         62 non-null     float64
 5   units             63 non-null     float64
 6   yoy_units         64 non-null     float64
 7   headquarter       68 non-null     object
 8   segment           71 non-null     object
 9   segment_category  70 non-null     object
dtypes: float64(4), int64(1), object(5)
memory usage: 6.4+ KB

In [35]:
df2.describe()

          rank      sales  yoy_sales         units  yoy_units
count  80.0000  67.000000  62.000000     63.000000  64.000000
mean   40.5000  18.370149   2.683871  21236.380952   2.653125
std    23.2379   8.778521   3.877687  10193.055065   3.178348
min     1.0000   5.200000  -4.500000   6044.000000  -2.800000
25%    20.7500  11.000000  -0.675000  12523.500000   0.350000
50%    40.5000  18.500000   3.000000  19840.000000   2.200000
75%    60.2500  25.650000   5.375000  30015.000000   5.425000
max    80.0000  35.000000   9.700000  39436.000000   8.000000

In [36]:
#handling missing data values

In [37]:
df2.isnull()
#it finds the presence of null values

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
75,False,False,False,True,False,False,True,False,False,False
76,False,True,False,False,False,False,False,False,False,False
77,False,False,False,False,False,True,False,False,False,False
78,False,False,False,False,False,True,True,False,False,False
79,False,False,False,False,False,False,True,False,False,False

In [38]:
df2.isnull().sum()
#find the number of null values of each column

rank                 0
restaurant          14
content             15
sales               13
yoy_sales           18
units               17
yoy_units           16
headquarter         12
segment              9
segment_category    10
dtype: int64

In [39]:
print(df2.isnull().sum().sum())
#sum of total null values

124

In [40]:
df2.shape

(80, 10)

In [41]:
#dropping rows with NaN values
df3=df2.dropna(axis=0) #axis =0 means it removes rows
df3
#removes the rows with null values and stores the data in df3

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
7,8,McDonald's,Pizza Delivery,6.1,6.9,30338.0,1.9,USA,Quick Service,Beverage
10,11,Starbucks,Pizza Delivery,10.6,4.2,24178.0,2.2,USA,Cafe,Beverage
12,13,Costa Coffee,Sandwiches,16.0,-0.7,17166.0,3.4,USA,Quick Service,Fast Food
17,18,Costa Coffee,Sandwiches,28.2,2.6,31849.0,5.7,USA,Cafe,Beverage
20,21,Dunkin',Sandwiches,9.0,7.8,20640.0,-0.3,USA,Delivery,Beverage
27,28,Dunkin',Coffee & Beverages,21.4,9.2,36103.0,1.8,USA,Delivery,Beverage
29,30,Dunkin',Sandwiches,25.6,5.9,39436.0,-1.0,USA,Cafe,Beverage
59,60,Domino's,Sandwiches,5.2,3.3,12311.0,0.2,USA,Quick Service,Fast Food
63,64,Burger King,Fried Chicken,18.5,1.3,35021.0,-2.0,USA,Delivery,Pizza

In [42]:
df3.shape

(12, 10)

In [43]:
df4=df2.dropna(axis=1) #axis =1 means columns  will be removed
df4

    rank
0      1
1      2
2      3
3      4
4      5
..   ...
75    76
76    77
77    78
78    79
79    80

[80 rows x 1 columns]

In [44]:
df4.shape

(80, 1)

In [45]:
#remove if 'any' row value is null then remove that row
df5=df2.dropna(how='any')
print (df5)
df5.shape

    rank    restaurant             content  sales  yoy_sales    units  \
1      2    McDonald's          Sandwiches   31.3       -4.5  29515.0
2      3   Burger King   Fast Food Burgers   33.6        3.1  16921.0
3      4        Subway       Fried Chicken    5.8       -0.2   8233.0
7      8    McDonald's      Pizza Delivery    6.1        6.9  30338.0
10    11     Starbucks      Pizza Delivery   10.6        4.2  24178.0
12    13  Costa Coffee          Sandwiches   16.0       -0.7  17166.0
17    18  Costa Coffee          Sandwiches   28.2        2.6  31849.0
20    21       Dunkin'          Sandwiches    9.0        7.8  20640.0
27    28       Dunkin'  Coffee & Beverages   21.4        9.2  36103.0
29    30       Dunkin'          Sandwiches   25.6        5.9  39436.0
59    60      Domino's          Sandwiches    5.2        3.3  12311.0
63    64   Burger King       Fried Chicken   18.5        1.3  35021.0

    yoy_units headquarter        segment segment_category
1         1.0         USA           Cafe        Fast Food
2         3.4         USA           Cafe         Beverage
3         7.8         USA           Cafe        Fast Food
7         1.9         USA  Quick Service         Beverage
10        2.2         USA           Cafe         Beverage
12        3.4         USA  Quick Service        Fast Food
17        5.7         USA           Cafe         Beverage
20       -0.3         USA       Delivery         Beverage
27        1.8         USA       Delivery         Beverage
29       -1.0         USA           Cafe         Beverage
59        0.2         USA  Quick Service        Fast Food
63       -2.0         USA       Delivery            Pizza

(12, 10)

In [46]:
df5=df2.dropna(how = 'all')
print (df5)
df5.shape
# remove the row if the enitre row is empty
# in this dataset no row is entirely NULL

    rank    restaurant             content  sales  yoy_sales    units  \
0      1        Subway       Fried Chicken   20.0       -0.3   8274.0
1      2    McDonald's          Sandwiches   31.3       -4.5  29515.0
2      3   Burger King   Fast Food Burgers   33.6        3.1  16921.0
3      4        Subway       Fried Chicken    5.8       -0.2   8233.0
4      5  Costa Coffee      Pizza Delivery   32.0       -3.4      NaN
..   ...           ...                 ...    ...        ...      ...
75    76    McDonald's      Pizza Delivery    NaN        9.1  24822.0
76    77           NaN   Fast Food Burgers   12.0       -2.8  15876.0
77    78     Taco Bell      Pizza Delivery   29.4        5.3      NaN
78    79   Burger King  Coffee & Beverages   29.5       -0.3      NaN
79    80      Domino's   Fast Food Burgers   10.4       -2.3  13005.0

    yoy_units headquarter        segment segment_category
0         1.2         USA            NaN        Fast Food
1         1.0         USA           Cafe        Fast Food
2         3.4         USA           Cafe         Beverage
3         7.8         USA           Cafe        Fast Food
4         0.1         USA       Delivery         Beverage
..        ...         ...            ...              ...
75        NaN         USA           Cafe        Fast Food
76        5.2         USA  Quick Service         Beverage
77        2.5         USA       Delivery        Fast Food
78        NaN         USA  Quick Service            Pizza
79        NaN         USA       Delivery         Beverage

[80 rows x 10 columns]

(80, 10)

In [47]:
df2.dropna(inplace = True)
print(df2)
df2.shape
#replace the original dataframe and create a new data frmae that do not have any null values

    rank    restaurant             content  sales  yoy_sales    units  \
1      2    McDonald's          Sandwiches   31.3       -4.5  29515.0
2      3   Burger King   Fast Food Burgers   33.6        3.1  16921.0
3      4        Subway       Fried Chicken    5.8       -0.2   8233.0
7      8    McDonald's      Pizza Delivery    6.1        6.9  30338.0
10    11     Starbucks      Pizza Delivery   10.6        4.2  24178.0
12    13  Costa Coffee          Sandwiches   16.0       -0.7  17166.0
17    18  Costa Coffee          Sandwiches   28.2        2.6  31849.0
20    21       Dunkin'          Sandwiches    9.0        7.8  20640.0
27    28       Dunkin'  Coffee & Beverages   21.4        9.2  36103.0
29    30       Dunkin'          Sandwiches   25.6        5.9  39436.0
59    60      Domino's          Sandwiches    5.2        3.3  12311.0
63    64   Burger King       Fried Chicken   18.5        1.3  35021.0

    yoy_units headquarter        segment segment_category
1         1.0         USA           Cafe        Fast Food
2         3.4         USA           Cafe         Beverage
3         7.8         USA           Cafe        Fast Food
7         1.9         USA  Quick Service         Beverage
10        2.2         USA           Cafe         Beverage
12        3.4         USA  Quick Service        Fast Food
17        5.7         USA           Cafe         Beverage
20       -0.3         USA       Delivery         Beverage
27        1.8         USA       Delivery         Beverage
29       -1.0         USA           Cafe         Beverage
59        0.2         USA  Quick Service        Fast Food
63       -2.0         USA       Delivery            Pizza

(12, 10)