In [1]:
#filling the Null Vlues
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\HP\Downloads\restaurant_data.csv')
df.head()
df

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,NaN,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,NaN,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,NaN,9.1,24822.0,NaN,USA,Cafe,Fast Food
76,77,NaN,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,NaN,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,NaN,NaN,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,NaN,USA,Delivery,Beverage

In [3]:
df.isnull().sum()
#null value in each column

rank                 0
restaurant          14
content             15
sales               13
yoy_sales           18
units               17
yoy_units           16
headquarter         12
segment              9
segment_category    10
dtype: int64

In [4]:
#as null removes the entire row it is costing the data which we can't afford
df.fillna(0)
#fill all the null values with zero

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,0,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,0.0,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,0.0,9.1,24822.0,0.0,USA,Cafe,Fast Food
76,77,0,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,0.0,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,0.0,0.0,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,0.0,USA,Delivery,Beverage

In [5]:
df.fillna(2)
#fill all the null values with two

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,2,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,2.0,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,2.0,9.1,24822.0,2.0,USA,Cafe,Fast Food
76,77,2,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,2.0,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,2.0,2.0,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,2.0,USA,Delivery,Beverage

In [6]:
df.fillna({'yoy_units':'none', 'segment':0})
#fill the specified column with given values

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,0,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,NaN,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,NaN,9.1,24822.0,none,USA,Cafe,Fast Food
76,77,NaN,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,NaN,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,NaN,none,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,none,USA,Delivery,Beverage

In [7]:
#df.fillna(method='ffill', axis=0) #this might break in future
df.ffill(axis=0) #by default
#the method ffill=forward fill it will fill the null values with the previous row value

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,NaN,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,8233.0,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,27.2,9.1,24822.0,-0.1,USA,Cafe,Fast Food
76,77,McDonald's,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,15876.0,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,15876.0,2.5,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,2.5,USA,Delivery,Beverage

In [8]:
df.ffill(axis=1)
#the method ffill=forward fill, it will fill the null values with the previous column value

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,USA,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,-3.4,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,Pizza Delivery,9.1,24822.0,24822.0,USA,Cafe,Fast Food
76,77,77,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,5.3,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,-0.3,-0.3,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,13005.0,USA,Delivery,Beverage

In [9]:
df['yoy_units'].fillna(value=df['yoy_units'].mean())
#fill the values of the particular column with mean values

0     1.200000
1     1.000000
2     3.400000
3     7.800000
4     0.100000
        ...
75    2.653125
76    5.200000
77    2.500000
78    2.653125
79    2.653125
Name: yoy_units, Length: 80, dtype: float64

In [10]:
#df.fillna(method='bfill')
df.bfill(axis=0)
#fill the null values with the next row value

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,Cafe,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,27000.0,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,12.0,9.1,24822.0,5.2,USA,Cafe,Fast Food
76,77,Taco Bell,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,13005.0,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,13005.0,NaN,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,NaN,USA,Delivery,Beverage

In [11]:
df.bfill(axis=1)
#fill the null values with the next column value

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,Fast Food,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,0.1,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,9.1,9.1,24822.0,USA,USA,Cafe,Fast Food
76,77,Fast Food Burgers,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,2.5,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,USA,USA,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,USA,USA,Delivery,Beverage

In [12]:
#df.fillna(method = 'bfill', inplace = True)
df.bfill(inplace = True)
df
#updates the df directly, no new DataFrame is created

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,Cafe,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,27000.0,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,12.0,9.1,24822.0,5.2,USA,Cafe,Fast Food
76,77,Taco Bell,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,13005.0,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,13005.0,NaN,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,NaN,USA,Delivery,Beverage

In [13]:
#df.replace(to_replace=-0.3, value=-0.4)
#replace a particular va;ue with other value
#shortcut
df.replace(-0.3,-0.4)

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.4,8274.0,1.2,USA,Cafe,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,27000.0,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,12.0,9.1,24822.0,5.2,USA,Cafe,Fast Food
76,77,Taco Bell,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,13005.0,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.4,13005.0,NaN,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,NaN,USA,Delivery,Beverage

In [14]:
df =df.drop_duplicates()
#chaeck identical rows and delete them
df

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,Cafe,Fast Food
1,2,McDonald's,Sandwiches,31.3,-4.5,29515.0,1.0,USA,Cafe,Fast Food
2,3,Burger King,Fast Food Burgers,33.6,3.1,16921.0,3.4,USA,Cafe,Beverage
3,4,Subway,Fried Chicken,5.8,-0.2,8233.0,7.8,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,27000.0,0.1,USA,Delivery,Beverage
...,...,...,...,...,...,...,...,...,...,...
75,76,McDonald's,Pizza Delivery,12.0,9.1,24822.0,5.2,USA,Cafe,Fast Food
76,77,Taco Bell,Fast Food Burgers,12.0,-2.8,15876.0,5.2,USA,Quick Service,Beverage
77,78,Taco Bell,Pizza Delivery,29.4,5.3,13005.0,2.5,USA,Delivery,Fast Food
78,79,Burger King,Coffee & Beverages,29.5,-0.3,13005.0,NaN,USA,Quick Service,Pizza
79,80,Domino's,Fast Food Burgers,10.4,-2.3,13005.0,NaN,USA,Delivery,Beverage

In [15]:
#removes rows based on column
df = df.drop_duplicates(subset='segment')
df

,rank,restaurant,content,sales,yoy_sales,units,yoy_units,headquarter,segment,segment_category
0,1,Subway,Fried Chicken,20.0,-0.3,8274.0,1.2,USA,Cafe,Fast Food
4,5,Costa Coffee,Pizza Delivery,32.0,-3.4,27000.0,0.1,USA,Delivery,Beverage
6,7,McDonald's,Fast Food Burgers,6.1,2.2,17725.0,1.9,USA,Quick Service,Fast Food