In [7]:
import pandas as pd

# Main DataFrame
df = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Aman', 'Riya', 'Rahul', 'Neha', 'Simran'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi'],
    'Salary': [50000, 60000, 55000, 65000, 70000],
    'Marks': [85, 90, 78, 88, 95],
    'Month': ['Jan', 'Jan', 'Feb', 'Feb', 'Jan'],
    'Sales': [200, 300, 250, 400, 350]
})

# Second DataFrame for merge
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Department': ['HR', 'IT', 'Finance', 'Marketing']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3, 5],
    'Bonus': [5000, 6000, 7000, 8000]
})

print(df)

   ID    Name    City  Salary  Marks Month  Sales
0   1    Aman   Delhi   50000     85   Jan    200
1   2    Riya  Mumbai   60000     90   Jan    300
2   3   Rahul   Delhi   55000     78   Feb    250
3   4    Neha  Mumbai   65000     88   Feb    400
4   5  Simran   Delhi   70000     95   Jan    350

In [8]:
result = df.groupby('City')['Salary'].mean()
print(result)
#groupby() is used to split a DataFrame into groups based columns
#to perfrom operations like sum, mean, count, etc.to each group separately

City
Delhi     58333.333333
Mumbai    62500.000000
Name: Salary, dtype: float64

In [14]:
pd.merge(df1, df2, on='ID')
#Combines two datasets (df1 and df2) based on a common column ID.

   ID Department  Bonus
0   1         HR   5000
1   2         IT   6000
2   3    Finance   7000

In [16]:
df.pivot_table(values='Sales', index='Month')
#Creates a summary table (like Excel pivot table).

            Sales
Month
Feb    325.000000
Jan    283.333333

In [17]:
df.sort_values('Marks', ascending=False)
#Sorts data based on Marks column in descending order (highest first).

   ID    Name    City  Salary  Marks Month  Sales
4   5  Simran   Delhi   70000     95   Jan    350
1   2    Riya  Mumbai   60000     90   Jan    300
3   4    Neha  Mumbai   65000     88   Feb    400
0   1    Aman   Delhi   50000     85   Jan    200
2   3   Rahul   Delhi   55000     78   Feb    250

In [21]:
df['Grade'] = df['Marks'].apply(
    lambda x: 'A' if x>=85 else 'B')
df
#apply runs the function on every value
#lambda is a way to create a small function without giving it a name

   ID    Name    City  Salary  Marks Month  Sales Grade
0   1    Aman   Delhi   50000     85   Jan    200     A
1   2    Riya  Mumbai   60000     90   Jan    300     A
2   3   Rahul   Delhi   55000     78   Feb    250     B
3   4    Neha  Mumbai   65000     88   Feb    400     A
4   5  Simran   Delhi   70000     95   Jan    350     A